export const APP_OPEN_MODAL = "APP_OPEN_MODAL"
export const APP_CLOSE_MODAL = "APP_CLOSE_MODAL"
export const APP_SWITCH_SIDEBAR = "APP_SWITCH_SIDEBAR"
export const APP_LAUNCH_SNACKBAR = 'APP_LAUNCH_SNACKBAR'
export const APP_CLOSE_SNACKBAR = 'APP_CLOSE_SNACKBAR'
export const APP_CHANGE_SNACKBAR_MESSAGE = 'APP_CHANGE_SNACKBAR_MESSAGE'