export const GET_CARDS = "GET_CARDS"
export const FILTER_CARD = "FILTER_CARD"
export const SET_CARDS = "SET_CARDS"
export const FETCHING_CARDS = "FETCHING"
export const FILTER_CARD_TECH = "FILTER_CARD_TECH"
